name: t89
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_bloc: ^8.1.1

  # Dependency injection
  get_it: ^7.2.0

  # Networking
  http: ^1.2.1

  # Adaptive UI
  responsive_sizer: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Add assets or fonts here if needed
